table 'DADOS_ATIVIDADE (2)'
	lineageTag: 20b2be64-4a51-4b2a-9919-0529a6974a4c

	column Column1
		dataType: string
		lineageTag: dd98726a-6847-4906-8e3d-6768fa2c9620
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: c76b325c-3b29-4364-8097-3a664320de17
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: bfe42501-0b79-4d28-973b-0e201eecca1a
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 1492931b-d5a3-480b-a363-ebcb4c565a98
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 27d6b932-dc3c-4e94-9085-a1b058562225
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 73e0ab8e-c2b2-4d78-bcd5-2905aec2b9c6
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: acd89c50-2858-4ee6-bb98-c14ad44944f1
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 7c0b121c-a61d-4662-87e7-ed2e582893fa
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 4ed2b22a-6f6c-4569-8cf5-966e4eb3a19d
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 8b9aa686-0282-4c1f-94ab-3fae240e8c49
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: b16ba016-95df-40b1-8c62-277d174683e6
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 75c74e30-7d75-46b9-a404-d92bf5d8ed4f
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 55f7d402-25e3-4918-97c8-955ab4f22d1c
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: f8e0e543-629c-4c0d-922e-496d46e9e80b
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: a430c96f-94f1-4fc7-a99b-bea408e15d8e
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: a377a960-bfef-407b-96d1-64bcd5f10f26
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: 1c690d08-8d5a-4eca-883b-192992b2a3be
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 0b65ab9e-672d-4f81-9507-ba61851f8e88
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: 83340186-e842-4beb-a385-405169491024
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: aa48d185-556a-4f22-9e09-de8ff2768b32
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: 9745ed67-a28e-43c0-9ba6-19dd6d2560e9
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column Column22
		dataType: string
		lineageTag: d4afd4c6-8eb1-4089-83f6-bb5012bb5c53
		summarizeBy: none
		sourceColumn: Column22

		annotation SummarizationSetBy = Automatic

	column Column23
		dataType: string
		lineageTag: bf332c03-039e-4d65-a9b8-bfe20fac000f
		summarizeBy: none
		sourceColumn: Column23

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: 29357a59-6de8-4b52-af05-d10a36eed6be
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	partition 'DADOS_ATIVIDADE (2)' = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\thorc\Downloads\DADOS_ATIVIDADE.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

